### ISSUE TITLE
git not found

### ISSUE THREAD

**Issue by Chiogros** [hedgedoc/container#279]
Hi,

Using given `docker-compose.yml`, I get an `/bin/sh: 1: git: not found` while `docker-compose up`ing.
The error comes from the `app` container.

Versions:
- docker: 20.10.7
- docker-compose: 1.25.0

Thanks.

**Comment by ErikMichelson** [comment]
This error can safely be ignored.

As a background: HedgeDoc tries to determine the source repository URL at startup for showing an appropriate link in the footer of the intro page. This uses the git binary. The link has a default fallback which is used in cases where the URL could not be fetched, like because of missing git.

However, we should evaluate whether we could disable the check or at least suppress the error message when running within a container.
